# Generated by Django 6.0.4 on 2026-04-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default='general', max_length=100),
            preserve_default=False,
        ),
    ]
